#!/usr/bin/env node
"use strict";

const jsonValidatorDuplicatedKeys = require("json-validator-duplicated-keys");
const ObjectID = require("bson-objectid");

const jsongo = require("./jsongo.js");

const assert = require("assert");
const fs = require("fs");
const Path = require("path");

/*
  jsongo fsck
    walk .json files
      all JSON parsable
      all arrays of records
    keys are sorted
    every record has an _id
    all _id's are unique
    every reference is valid
  jsongo rewrite-id <collection> <oldid> <newid>
*/

(function main() {
  const cmd = process.argv[2];
  switch (cmd) {
    case "objectid":
      console.log(ObjectID().toHexString());
      break;
    case "rewrite-id":
      rewriteId({
        collectionName: process.argv[3],
        oldID: process.argv[4],
        newID: process.argv[5]
      });
      break;
    case "fmt":
      fmt();
      break;
    case "e":
    case "eval":
      evalCmd(process.argv[3]);
      break;
    case "fsck":
      fsck();
      break;
    case "ls":
      console.log(
        JSON.stringify(
          _jsonFileNames().map(fileName =>
            fileName.substr(0, fileName.length - 5)
          ),
          null,
          2
        )
      );
      break;
    default:
      console.error(`ERROR unknown command: "${cmd}"`);
      process.exit(1);
  }
})();

function rewriteId({ collectionName, oldID, newID }) {
  // TODO preflight to ensure newID is unqiue in collection.

  assert.notStrictEqual(collectionName, undefined);
  assert.notStrictEqual(oldID, undefined);
  assert.notStrictEqual(newID, undefined);

  const collectionRelationKey = `${collectionName}_id`;

  for (const jsonFileName of _jsonFileNames()) {
    const jsonBuf = fs.readFileSync(jsonFileName);
    const json = JSON.parse(jsonBuf);
    let dirty = false;

    if (Path.parse(jsonFileName).name === collectionName) {
      // The collection that hold the document with oldID.
      for (const doc of json) {
        if (doc._id === oldID) {
          doc._id = newID;
          dirty = true;
        }
      }
    } else {
      // A collection that may have a reference to oldID.
      for (const document of json) {
        let value = document[collectionRelationKey];
        if (value === undefined) continue;

        if (value instanceof Array) {
          const idx = value.indexOf(oldID);
          if (idx !== -1) {
            value[idx] = newID;
            dirty = true;
          }
        } else if (value === oldID) {
          document[collectionRelationKey] = newID;
          dirty = true;
        }
      }
    }
    if (dirty) {
      fs.writeFileSync(jsonFileName, JSON.stringify(json, null, 2));
    }
  }
}

function fsck() {
  const jsonFileNames = fs
    .readdirSync(".")
    .filter(fileName => fileName.endsWith(".json"));
  for (const jsonFileName of _jsonFileNames()) {
    console.log(`checking ${jsonFileName}`);
    const jsonBuf = fs.readFileSync(jsonFileName);
    const json = JSON.parse(jsonBuf);
    jsonValidatorDuplicatedKeys.validate(jsonBuf);

    // for (const record of json) {
    //   console.log(`  ${record._id}`);
    // }
  }
}

function fmt() {
  const db = jsongo.db({ dirPath: "." });
  for (const jsonFileName of _jsonFileNames()) {
    const collectionName = Path.parse(jsonFileName).name;
    db[collectionName].docs();
  }
  db.save();
}

function evalCmd(cmd) {
  const db = jsongo.db({ dirPath: "." });
  const cmdFunctionStr = `(function cmdFunctionStr(){
    "use strict";
    return (${cmd});
  })()`;
  console.log(eval(cmdFunctionStr));
}

function _jsonFileNames() {
  return fs.readdirSync(".").filter(fileName => fileName.endsWith(".json"));
}
